apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: scstor1
provisioner: disk.csi.azure.com
parameters:
  storageaccounttype: Standard_LRS
  kind: managed
  resourceGroup: aksrgstorage
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
